In [1]:
from sklearn.datasets import fetch_openml 
mnist = fetch_openml('mnist_784', version=1)

/Users/eryk/miniconda3/envs/ml/lib/python3.10/site-packages/sklearn/datasets/_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [2]:
import numpy as np
print((np.array(mnist.data.loc[0]).reshape(28, 28) > 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 

In [3]:
X = mnist.data
y = mnist.target

In [4]:
y = y.sort_values()

In [5]:
X = X.reindex(y.index)

In [6]:
X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(56000, 784) (56000,)
(14000, 784) (14000,)


In [7]:
print(y_train.unique())
print(y_test.unique())

['0', '1', '2', '3', '4', '5', '6', '7']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']
['7', '8', '9']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, random_state=42)

In [9]:
print(y_train.unique().sort_values())
print(y_test.unique().sort_values())

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']


In [10]:
y0_train = (y_train == '0')
y0_test = (y_test == '0')

In [11]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y0_train)

SGDClassifier(random_state=42)

In [12]:
y_train_pred = sgd_clf.predict(X_train)
y_test_pred = sgd_clf.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score
y_train_acc = accuracy_score(y0_train, y_train_pred)
y_test_acc = accuracy_score(y0_test, y_test_pred)

In [14]:
import pickle
acc = [y_train_acc, y_test_acc]
with open('sgd_acc.pkl', 'wb') as acc_pickle:
    pickle.dump(acc, acc_pickle)

In [15]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(sgd_clf, X_train, y0_train, cv=3, scoring='accuracy', n_jobs=-1)

In [16]:
with open('sgd_cva.pkl', 'wb') as cva_pickle:
    pickle.dump(score, cva_pickle)

In [17]:
sgd_clf_all = SGDClassifier(random_state=42)

In [18]:
sgd_clf.fit(X_train, y_train)

SGDClassifier(random_state=42)

In [19]:
y_test_pred_all = sgd_clf.predict(X_test)

In [20]:
accuracy_score(y_test, y_test_pred_all)

0.8687857142857143

In [21]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test, y_test_pred_all)

In [22]:
conf_matrix

array([[1318,    0,    1,    0,    1,    7,   10,    0,   28,    0],
       [   1, 1370,   12,    4,    2,    4,    6,    3,  180,   10],
       [  18,    8, 1111,   20,   18,    9,   36,    8,  152,    9],
       [   4,    4,   29, 1066,   11,  119,    3,    6,  130,   22],
       [   4,    0,    1,    1, 1230,    8,   17,    1,   49,   55],
       [  15,    1,    4,   34,   23, 1065,   30,    3,  119,   16],
       [   5,    1,    7,    0,    8,   23, 1323,    0,   32,    0],
       [   6,    0,   13,    1,   20,    4,    0, 1241,   68,   90],
       [   9,    5,    7,   11,    7,   30,    3,    1, 1284,   13],
       [   5,    0,    3,    7,   41,   15,    0,   32,  114, 1155]])

In [23]:
with open('sgd_cmx.pkl', 'wb') as cmx_pickle:
    pickle.dump(conf_matrix, cmx_pickle)